### ISSUE TITLE
Unable to save training data extracted with gradient method

### ISSUE THREAD

**Issue by anusha-2804** [delvendahl/miniML#10]
Hi,
I was able to smoothly run the code and save the file with the template method. However, when the same input file is processed with the gradient method,  I am unable to save it. This is the error message I get: 

ValueError                                Traceback (most recent call last)
Cell In[22], line 2
      1 # Save the result
----> 2 x = np.array(events)
      3 y = np.array(scores)
      4 indices = np.array(idx)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (303,) + inhomogeneous part.

Can you please help me solve this issue?

**Comment by poneil-UZH** [comment]
Just to clarify, this is to extract training data to train a model, right?

Regarding the error message, I had a quick look at the code. With the example data provided by us I can extract and save training data and open it. I assume that you are trying to extract data from your own data? Without the data I cannot reproduce the error.

But in any case, the error occurs because "events" is a list that contains arrays. Each array corresponds to an extracted stretch of data. They should all have the length of win_size (but in your case they likely don't). The error occurs when the list of arrays is converted into an array of arrays. This only works if all arrays have the same length, which probably is not the case here, and leads to the error. At least that's my guess without being able to reproduce the error.

My best guess is that the problem comes from the following line:

for ind, location in enumerate(peaks):
&nbsp;if location < trace.data.shape[0] - int(win_size*1.5):
&nbsp;&nbsp;event = copy.deepcopy(trace.data[location-int(1/6*win_size):location+int(5/6*win_size)])

if location is very close to the start of the data, it may cause issues because we extract:
 location-int(1/6*win_size) : location+int(5/6*win_size)

This happens twice, when we extract clear events and when we extract unclear events, FPs and so on.

You can replace the two parts with the following snippet:

for ind, location in enumerate(peaks):
&nbsp;if location < trace.data.shape[0] - int(win_size*1.5) and location > int(1/2*win_size):
&nbsp;&nbsp;event = copy.deepcopy(trace.data[location-int(1/6*win_size):location+int(5/6*win_size)])


I have updated the file on GitHub as well. In case you can just pull the changes and hopefully it fixes the issue. But let me know if it persists.

**Comment by anusha-2804** [comment]
Hi,
Yes I mean to extract training data to train the model.

I tried to implement what you suggested but the same problem persists.

However I think I found where it is coming from. I think the issue comes when you change the window size from 600 to anything else. 
I tried this also with the example data that you have provided. I had no issues saving the extracted data when the window size was set to 600. But when I change it to anything else, then the same issue appears. 

Best regards,
Anusha.

**Comment by poneil-UZH** [comment]
Ok, I believe now I found the issue (at least I could reproduce the error). The following lead to rounding issues:

event = copy.deepcopy(trace.data[location-int(1/6*win_size):location+int(5/6*win_size)])

I replaced it with the following:

left_buffer = int(1/6*win_size)
right_buffer = win_size - left_buffer
event = copy.deepcopy(trace.data[location-left_buffer:location+right_buffer])

The file is already updated, I hope this fixes the issue, but let me know if it persists for you.

**Comment by anusha-2804** [comment]
Hi,
Yes the issue is fixed for me now.
Thank you so much!
